import json
data = {"Pre-deployment Documents": ["CSE Internship Orientation Certificate", "Student Authorization for Release of Personal Information", "Resume", "Medical Clearance", "Mock Interview Certification", "Psychological Exam", "Good Moral Certificate", "Enrollment Permit", "Recommendation / Endorsement Letter", "Acceptance Letter", "Certificate of Employment – Start of the Semester (For working students)", "Company ID (For working students)"], "Upon Deployment Documents": ["Notarized Parental Consent", "Communication with your OJT Adviser (Attendance)", "Signed Internship Plan", "Weekly Accomplishment Reports", "Monthly Attendance Monitoring Sheets"], "Post-Deployment Documents": ["Student Evaluation of the On-the-Job Training", "Practicum / Internship Performance Evaluation", "Certificate of Training / Certificate of Completion", "Certificate of Employment – End of the Semester (For working students)"], "Other Documents": ["Notarized Internship Agreement", "Notarized Memorandum of Agreement", "Notarized Data Use and Protection Agreement Annex", "Company Background / Profile", "Job Description", "Overtime Work Request Forms", "Saturday Work Request Forms", "Holiday Work Request Forms", "Term End Self-Assessment and Evaluation", "Practicum/Internship Reflection", "Matrix for Computing OJT Hours", "Practicum Internship Checklist", "Labor Education for Graduating Students Certificate", "PSITE NCR International Computing Studies Congress 2025 Certificate", "Other Certificates of Seminars and Workshops Attended", "Other Proof of Employment (For Working Students)", "Sample Works or Pictures"]}
html = ""
for section, items in data.items():
    html += f"        <section class=\\"blog-posts\\" style=\\"margin-bottom: 40px;\\">\\n"
    html += f"          <h3 class=\\"h3\\" style=\\"margin-bottom: 20px; color: var(--white-2);\\">{section}</h3>\\n"
    html += f"          <ul class=\\"blog-posts-list\\">\\n"
    for item in items:
        html += f"""            <li class=\\"blog-post-item\\">\\n              <a href=\\"#\\">\\n                <figure class=\\"blog-banner-box\\">\\n                  <img src=\\"./assets/images/blog-1.jpg\\" alt=\\"{item}\\" loading=\\"lazy\\" class=\\"req-img\\">\\n                </figure>\\n                <div class=\\"blog-content\\">\\n                  <div class=\\"blog-meta\\">\\n                    <p class=\\"blog-category\\">Requirement</p>\\n                  </div>\\n                  <h3 class=\\"h3 blog-item-title\\">{item}</h3>\\n                  <p class=\\"blog-text\\">Click to view document.</p>\\n                </div>\\n              </a>\\n              \\n            </li>\\n"""
    html += f"          </ul>\\n"
    html += f"        </section>\\n\\n"
with open("req.html", "w", encoding="utf-8") as f:
    f.write(html)
